### ISSUE TITLE
Is it possible to create Mazes in the current version?

### ISSUE THREAD

**Issue by ulkunderscore** [Ivorforce/RecurrentComplex#105]
I'm unable to create a simple maze following the instructions on the wiki and the one [outdated video](https://www.youtube.com/watch?v=vSudNS55k3M) I could find on youtube. I didn't watch the Minecraft Alpha video linked to on the "how to build a maze" guide on the wiki since it is muted due to copyright infringement, so if there was any vital information in threre, please do tell.
The maze doesn't generate. I did all the Trial & Error I could think of and did it again after you fixed the ID bug I reported yesterday. Would you please confirm that it is possible to create working mazes in v1.2.2 or maybe even take look at my [attempt at a simple hedge maze](http://s000.tinyupload.com/index.php?file_id=80985199971927223428)?

**Comment by Ivorforce** [comment]
You're missing 3 things.

Firstly, your maze needs an entry or exit - a point from which to start the maze.

Secondly, your components all have room size 0 to 3. Every one of them, as they are base components, need to be size 1, 1, 1 (areas 0, 0, 0 to 0, 0, 0). I get why you would get this wrong, I probably need to explain this better in the tutorial.

Thirdly, all your components are lacking their exits. Otherwise the algorithm doesn't know how to connect them.

I recommend looking at the StoneMaze components if you need examples of how it works.

**Comment by Ivorforce** [comment]
(I'm closing this because it's not an issue per se. If you have more questions feel free to ask.)

**Comment by ulkunderscore** [comment]
I got it now, thanks!
