### ISSUE TITLE
Leaves decaying immediately

### ISSUE THREAD

**Issue by whichonespink44** [Ivorforce/RecurrentComplex#111]
Leaves generated by some of RC's trees are decaying immediately.

At first, I thought this was just an issue in RTG worlds using the new [4.1.1.5 pre-release](https://cdn.discordapp.com/attachments/168326116761665536/241964488461385728/RTG-1.10.2-4.1.1.5-discord-prerelease-1.jar), but I tested some default worlds using just RC 1.2.2 & RC 1.2.3 (and FastLeafDecay), and it's happening in default worlds as well.

This happens even if the global toggle `treeLeavesDecay` is set to false.

From what I can see, it seems to be related to some of the trees not having supporting log blocks, but that might not be the case for every tree.

**Comment by TheDeviantCrafter** [comment]
Recurrent Complex may generate trees with leaves far enough away from the nearest log block that Fast Leaf Decay seems them as "floating." It could also be because RC generates trees with leaf blocks that are diagonal to other leaf blocks but not directly touching.

I don't have time to test this, but it's possible that Fast Leaf Decay does it's task differently than vanilla code. If it manually checks when leaves are floating rather than simply increasing the speed of random ticks on leaves (which is how vanilla Minecraft does it) it may not count leaf blocks that are diagonal to other leaf blocks, and may require blocks to be closer to a log than vanilla does.

If I'm correct, this is an issue with Fast Leaf Decay and not with Recurrent Complex.

**Comment by Ivorforce** [comment]
Yes, try reporting it to Fast Leaf Decay's author. treeLeavesDecay generates the leaf block with the decayable property set to false, which Fast Leaf Decay should honor. 
Also make sure that the leaves are actually spawning with the property set to false (by removing the fast leaf decay mod and generating some trees). Some people have reported the treeLeavesDecay option is ignored, though I cannot reproduce it currently.

**Comment by whichonespink44** [comment]
Just been doing more testing using only Forge 2099, RecurrentComplex 1.2.3, and IvToolkit 1.2.8.5 (no other mods), and I can confirm that leaves are still decaying immediately, regardless of whether `treeLeavesDecay` is true or false.

Looking at the trees that were decaying immediately, it's definitely happening due to there not being enough supporting log blocks:

![rc](https://cloud.githubusercontent.com/assets/10927161/19869246/6fbfa92e-9fa3-11e6-8320-6624686bd407.gif)

The first screenshot was taken just after the world first loaded, and the second screenshot was taken about 10 minutes later.

I don't know how many trees are missing supporting log blocks, but I'd say it's pretty significant. When I was testing with WorldEdit before this last batch of tests, I ran the `/remove items 1000` command, and it removed hundreds of items (saplings).

Since it's probably a massive job to re-design the trees to have supporting log blocks, it might be best to figure out why the `treeLeavesDecay` global toggle isn't working.

If there's anything I can do to help, just let me know. I know a lot of RTG's users also love running RC, and currently this is what's happening for them in RTG worlds:

![rtg_rc](https://cloud.githubusercontent.com/assets/10927161/19869607/f0f06de8-9fa4-11e6-9cb4-ae09243986c9.gif)

**Comment by Ivorforce** [comment]
Since 1.2.3.4 there's /#eval (which I may or may not have added for exactly this issue). 
Try /#eval global:treeLeavesDecay ingame and see if it outputs False. 
If False, do /#edit GenericTree, click Transformers, edit '1 Transformer' and see if at the bottom it states global:treeLeavesDecay as the Condition. Theoretically, one of these things should not be the case.

**Comment by whichonespink44** [comment]
When `treeLeavesDecay=true` in the configs, `/#eval global:treeLeavesDecay` outputs 'true' and the transformer condition is 'gen.type=sapling'

When `treeLeavesDecay=false` in the configs, `/#eval global:treeLeavesDecay` outputs 'false' and the transformer condition is 'gen.type=sapling'

**Comment by whichonespink44** [comment]
Correction, there are two '1 Transformer' sections in the GUI...

When treeLeavesDecay=true in the configs, /#eval global:treeLeavesDecay outputs 'true' and the **second** transformer 1 condition is 'global:treeLeavesDecay'

When treeLeavesDecay=false in the configs, /#eval global:treeLeavesDecay outputs 'false' and the **second** transformer 1 condition is 'global:treeLeavesDecay'

**Comment by Ivorforce** [comment]
That sounds correct, then. Systems are in place and working. I''m pretty sure the config should do its thing then.
Do the tree leaves spawn with decayable set to false? Because if that's the case, they should not despawn.

**Comment by whichonespink44** [comment]
Yes, they're despawning with treeLeavesDecay=false

**Comment by QuImUfu** [comment]
Oh, i got the problem. 
Every tree version other than GenericTree (eg. GenericTreeHuge, GenericTree1) does not check for global:treeLeavesDecay.

**Comment by Ivorforce** [comment]
I'm not sure what the issue is, because it always worked for me.
Try the latest nightly build though. I have moved some stuff around and added some more logging that might be helpful.

**Comment by QuImUfu** [comment]
No they do not check for it.
Just type /#edit GenericTree1 and look at the last transformer.
Either i am completely stupid or at least the version on GitHub does not check for global:treeLeavesDecay. 
You can also just open the json in eg. GenericTree1.rcst . 
You won't find even a mention of treeLeavesDecay. Because they do not check for it. 
If you open GenericTree.rcst you will find a mention of treeLeavesDecay in the json. Because if checks for it.
I added this check to all tree files and added an template for DeadTree. If you want to use it you can download it [here](https://dl.dropbox.com/s/yd5t4m5wmjyama0/active.zip). 
Caution: I used the templates without pressing [Customize: * ] afterwards. This is different than it was before. I can change this if you want me to.

**Comment by Ivorforce** [comment]
The trees use the tree transformer preset (as marked under "dataPreset"). The data (in "data") is there only as backup to approximate what the preset might have been in case it's missing. During the game it will load and use the most current version of the preset instead, so the file might not always be accurate.

**Comment by QuImUfu** [comment]
then there is some problem in the code for using the preset. 
Because it works with my files but does not work with yours.
I replaced them in the mod .jar file and everything worked as expected.

**Comment by Ivorforce** [comment]
Can you do /#write transformer_preset tree ACTIVE and send me the file that's written into structures/active?

**Comment by QuImUfu** [comment]
"/#write transformer_preset tree ACTIVE" always gives me the file that is currently in the jar under "/assets/reccomplex/structures/active/presets/transformer/tree.rcmt"
[here](http://paste.ee/p/RiNg8) is the log. it logs some warns at startup.

**Comment by Ivorforce** [comment]
Well, there we go: [22:32:02] [Client thread/WARN] [reccomplex]: Failed to find transformer preset preset: tree

I think I get the issue now. Working on a fix.

**Comment by Ivorforce** [comment]
If the issue is not fixed let me know, but making it lazy should do the trick. If it doesn't I'll need to revamp more of the loading system.

**Comment by QuImUfu** [comment]
Can confirm it is fixed.
Does work perfectly with the newest nightly.
