### ISSUE TITLE
[1.10.2] Invalid entity IDs

### ISSUE THREAD

**Issue by TheRandomLabs** [Ivorforce/RecurrentComplex#163]
This isn't gamebreaking, but the entity ID changes between 1.10.2 and 1.11.2 are causing this error:
`Error loading entity with ID 'minecraft:entity_id'`
[Here](https://github.com/Ivorforce/RecurrentComplex/blob/1.10/src/main/java/ivorius/reccomplex/world/gen/feature/structure/generic/GenericStructureInfo.java#L196) is where the error is occurring. Maybe you could check for a specific entity ID then convert it to the 1.10.2 version (e.g. minecraft:item becomes minecraft:Item).

**Comment by Ivorforce** [comment]
Can you please include a full log?

**Comment by TheRandomLabs** [comment]
The whole thing is way too big to include (20000+ lines), so here's the relevant part.
http://pastebin.com/7MLPCAQs

**Comment by Ivorforce** [comment]
I'm a bit confused about the log - it should either output 'Skipping entity' or 'An Entity x has thrown an exception during loading' closely before my error - especially since your log level is set to TRACE.
If you're on 1.10 
I'm guessing though you're correct about the IDs.

I won't be providing any forwards compatibility for 1.10 though. I may fix the specifically affected structure (though it doesn't seem too important), but entities added in 1.11 won't work in 1.10.
