### ISSUE TITLE
Terraqueous and HarvestCraft trees don't spawn in biomes RC add trees

### ISSUE THREAD

**Issue by Hypsellis** [Ivorforce/RecurrentComplex#175]
All the biomes where RC adds his trees prevents Terraqueous and HarvestCraft trees to spawn, mainly forest biomes.

**Comment by Hypsellis** [comment]
The menril trees from Integrated Dynamics don't spawn neither.

**Comment by Ivorforce** [comment]
That's sort of to be expected. The tree replacement system in Forge is really basic, and unless those mods spawn them in not as trees but as structures, there is no way to do both. I'm still waiting on https://github.com/MinecraftForge/MinecraftForge/pull/3318 to be pulled to fix some of those issues.

For now you can use the biomeGenerationMatcher to disable ReC trees in specific biomes if you need different ones to spawn, or you can export those trees as ReC structures and weigh them in again using the ReC spawning system.

**Comment by Hypsellis** [comment]
So why not generate your trees as structures ? It would solve all the problems.

**Comment by Ivorforce** [comment]
Because I want to replace vanilla trees with this system. If I were to simply add mine, it would quickly result in too many trees.

Plus, the biome should be the information point in determining how many trees a chunk contains, as that information is already provided. Structures would have to set up the values from scratch.
