### ISSUE TITLE
[1.11.2]File[1.3.1.1] Overworld gen in nether and underwater

### ISSUE THREAD

**Issue by teutates1989** [Ivorforce/RecurrentComplex#214]
Overworld gen seems to end up in weird places like underwater and in the nether.
they don't seem to replace water/nether based generation because those can still be find where you would expect them too. 

i tried BOP  world generator, ATG en Quark in all three instances this seems too happen now and then.

Using: 
atg-1.11.2-2.1.4
BiomesOPlenty-1.11.2-6.1.0.2226-universal
Quark-r1.2-92

A few examples.

![2017-05-25_21 18 52](https://cloud.githubusercontent.com/assets/11924154/26497945/98e26ff8-422d-11e7-82ad-6a21e4c97950.png)
![2017-05-26_08 51 09](https://cloud.githubusercontent.com/assets/11924154/26497946/98e369c6-422d-11e7-8484-7b914a878373.png)
![2017-05-26_08 56 32](https://cloud.githubusercontent.com/assets/11924154/26497947/98e3b778-422d-11e7-9eff-e86c98ecdd20.png)

**Comment by Ivorforce** [comment]
The 'underwater church' is, I believe, an underground structure that happened to spawn in the water. I might adjust the placer to make sure it always places in ground and never in water, but it's definitely unrelated to the nether thing.

I have explored for a good while and haven't found a structure in the nether. Did you perhaps modify the 'overworld' dimension preset?

**Comment by teutates1989** [comment]
ah because the underwater structure has waterfalls that work underwater i thought it didn't belong there.

According to the one who made the pack we just added the mod en use generated configs.
I don't know where to find the dimension preset. is it in the config ? 

I created a new profile with the same mods but i'm unable to reproduce the generation in the nether. 
So it seems something went wrong while creating the profile.

**Comment by Scratchman** [comment]
I'm experiencing the same problem on a 1.10.2 server. This is the first time I've explored the nether on the server because it's still in a testing phase.

forge-1.10.2-12.18.3.2297
RecurrentComplex-1.3.1.1-1.10

I've never edited any of the default RC structures, so i don;t see any reason they should be generating in the nether. The village structures generating in the nether are structures i've added to Minecraft/structures/active and i would have never set them to generate in the nether, i don't think i know how to. They seem to generate in pockets in the nether, I went for quite a while not finding any overworld structures then i found the village, shrine, etc all in the same area.

http://imgur.com/a/ez7xV

**Comment by GuntherDW** [comment]
Hmm, I'm the "pack dev" that @teutates1989 mentioned. It's just a "pack thrown together" to check out what's available in 1.11.2. As in as kitchen sink as you can get without much config editing. In fact the only config editing I did was make sure that only 1 type of copper, tin, basalt etc generated. Nothing in terms of gameplay or anything else yet.

And I've had it happen in much of the same way.
http://i.imgur.com/m7ITFdG.png
http://i.imgur.com/5MPyhDL.png

**Comment by teutates1989** [comment]
Forgecraft seems to have the same problem i noticed it on Soaryn stream.  
https://www.twitch.tv/videos/147589469?t=02h50m56s
https://www.twitch.tv/videos/147589469?t=02h54m40s

**Comment by Ivorforce** [comment]
I have a rough idea how this might happen. Before I do work on this though can you confirm this happens on 1.3.2.1? 

What I think might be the problem is that chunk generation is complementing structures that have been added to other dimensions. That means structures would be at the same coordinates in any (compatible) dimension. Could you check that if that is the case?

**Comment by GuntherDW** [comment]
I downloaded the 1.3.1.2 jar (I assume that's the version you meant?) from the curseforge page and it does (still) indeed happen cross-dimensionally.

http://i.imgur.com/yzdA39M.png
I then travelled back to the overworld to the same x/z and it generated over there as well.
http://i.imgur.com/MDnIFJa.png

**Comment by Scratchman** [comment]
Updated to the latest 1.10.2 RC and I'm not seeing any overworld structures in the nether.

Thanks for the fix. :)
