### ISSUE TITLE
Crash with Mystcraft

### ISSUE THREAD

**Issue by xJon** [Ivorforce/RecurrentComplex#22]
Is it RecurrentComplex' fault, or Mystcraft's fault?
http://pastebin.com/p7hBZTXr

**Comment by Ivorforce** [comment]
Looks a lot like FastCraft's fault, actually. MystCraft is probably completely unrelated, and I'm guessing the crash is caused by FastCraft not being able to handle chained chunk generation properly - which is an inconvenient thing to currently happen, but completely valid with the vanilla / Forge setup.

**Comment by xJon** [comment]
@Ivorforce The weird thing is that it didn't happen at all until I updated Mystcraft . Is it possible that Mystcraft has something to do with it? Or no way?
Thank you for the support!

**Comment by Ivorforce** [comment]
Hrmmm... Well, I'd recommend sending it to both of them either way, in case they have any better ideas. My best guess is, again, chained chunk generation, but it's hard to check since FastCraft is not only not open source, but also obfuscated.

**Comment by xJon** [comment]
@Ivorforce I see. I'll try, and if I'd find anything new I'll tell you.
Thanks, again :)
