### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xJon** [Ivorforce/RecurrentComplex#23]
A lot of the structures generated by RecurrentComplex have books in them, with different stories, if I'm not wrong.
I wanted to know who wrote the content of the books, because it's really something beyond only modding.
Thanks

**Comment by Ivorforce** [comment]
The books are randomly generated - currently there are two main types, generic books (just title + author) and poems. I do sort of plan on adding more types, just because it's an interesting diversion to make, but I don't know when, yet.

The code for generating poems is here: https://github.com/Ivorforce/RecurrentComplex/blob/master/src/main/java/ivorius/reccomplex/random/Poem.java

Apart from the language constructs, random variables and paragraphs, they are separated into themes consisting of certain words, found for example here:
https://github.com/Ivorforce/RecurrentComplex/blob/master/src/main/resources/assets/reccomplex/poemThemes/war.txt

So that's pretty much how it works. I technically made up the content and concept, but the books themselves are uniquely and procedurally generated. Most of them are pretty random, but I have to confess I actually liked one or two in the past, too, haha.

**Comment by xJon** [comment]
You don't see much of this in modded Minecraft.
The contect can sometimes be funny, sometimes..very creepy.

**Comment by Ivorforce** [comment]
I'm glad you feel that way. It's definitely fun to work on this kind of stuff, too.
