### ISSUE TITLE
[1.4.3.1] /#export <structurename> not inheriting old settings for updating structures

### ISSUE THREAD

**Issue by thephoenixlodge** [Ivorforce/RecurrentComplex#250]
Since updating, trying to use /#export to update small details on a previously built structure by including the structure name as an argument doesn't work as expected. Instead of retaining all the previous generation settings, it only fills in the name field. This makes editing structures a nuisance as you have to manually re-enter all the generation settings.
If this has just been changed to a different method, could this please be reflected on the wiki or somewhere?

**Comment by Ivorforce** [comment]
For these kinds of problems please use /help #export. The correct command now is /#export --from Structure.

**Comment by thephoenixlodge** [comment]
Yea... Cos it's not like /help isn't usually broken in modded or anything right?

**Comment by Ivorforce** [comment]
I don't know what's usually broken but it certainly isn't for Recurrent Complex :P

**Comment by QuImUfu** [comment]
no, i think thephoenixlodge is referring to the /help command being broken in many mods so it doesn't work at all in most bigger modpacks (at least in 1.7.10). Recurrent Complex does not break /help in any way. You could however introduce a command like /#help (only for RC commands) or something like this to make sure it works even if some mod screws up the general /help command.

**Comment by Ivorforce** [comment]
Uh... Can you give me an error log of one of the instances where it's broken? It's hard to imagine actually.

**Comment by QuImUfu** [comment]
It was fixed in this case, but https://bitbucket.org/ProfMobius/waila/issues/110/crash-with-help-command mentions one of these, there even is a mod to prevent derped mods from crashing MC:
https://github.com/matthewprenger/HelpFixer

I do not play a lot of modpacks but there are quite some users of the mod (see curse), and i remember having one broken mod in one of my modpacks as well but i must have deleted the modpack.
I do not think it is a very common issue in minecraft versions >=1.10.2. But it was at some point in 1.7.10.

**Comment by Ivorforce** [comment]
That explains why everyone wants me to add the documentation to the wiki. I think I'll add a comment about using /help there.

**Comment by Ivorforce** [comment]
After some consideration I swapped it around again: e42d56224bec57398c6090751ae91c0403c5a0fc

From the next version on, /#export Structure will again copy the structure's data and --id will override the id.
