### ISSUE TITLE
[MC 1.12.1] Cascading world gen lag in Extra Utils 2 Deep Dark dim

### ISSUE THREAD

**Issue by craft90** [Ivorforce/RecurrentComplex#270]
There's a lot of block lag in Deep Dark. The log seems to point out the issue being Recurrent Complex.

Here's the error log: https://pastebin.com/zu2VEx7x

**Comment by Ivorforce** [comment]
See #155 for cascading chunk generation.

However, cascading chunk generation won't cause block lag - it will cause generation lag. As long as you don't explore, it won't show itself, and even so it usually isn't critical the way it is currently. I'd assume your problem lies elsewhere, or at least partially.

**Comment by craft90** [comment]
I just wanna add a little something, now that I have updated this mod and Extra Utils to 1.12.2 this issue no longer occurs.
