### ISSUE TITLE
[Mod Issue]: Certain Carpenter's Blocks Don't Orientate Properly & Microparts Don't get "Scanned" and thus not transfered :/

### ISSUE THREAD

**Issue by Lanse505** [Ivorforce/RecurrentComplex#29]
As The Titel Describes :P

**Comment by Ivorforce** [comment]
FMP is currently on my 'won't support' list, since it does multiple things that divert from the normal MC API too much to support - see http://www.chickenbones.craftsaddle.org/Files/Other/ItemDevTool2.java.

If FMP is to be supported, someone has to fix FMP. A simple hack won't do here, I'm afraid.

What about the carpenter's blocks? What part exactly doesn't work? I could look into if it's fixable.

**Comment by fishmealx** [comment]
From playing with it for a bit, it seems that carpenter's blocks remember the number and type of block they are using as camouflage, but certain slopes don't rotate properly. At the very least the interior and exterior oblique slopes are messing up for me most of the time. The prism slope messed up once out of like 20 tries.

**Comment by Ivorforce** [comment]
Most of these can be fixed by the authors themselves if they implement the rotate() functionality of Forge [properly]. If rotation is off and it still rotates it's probably weird block placement behavior - usually unideal implementation on their part too.

**Comment by Ivorforce** [comment]
Anyway, I'm closing this as it's too general of an issue to be fixed properly. If you want to request generation compatibility for _specific_ mods (and the exact problem they have) I can look into it more closely if they get their own issues.
