### ISSUE TITLE
[SUGGESTION] Anti-Cheat option/block (No Placing or Breaking of Blocks)

### ISSUE THREAD

**Issue by TheSexyYeti** [Ivorforce/RecurrentComplex#447]
I wanna build elaborate dungeons. But I don't want the players to be able to cheat by breaking blocks or even placing blocks. So I suggest a new option in the structure generation menu. Or a separate block all together that when spawned in prevents players from placing and/or breaking blocks. Placing and breaking blocks can optionally be selected separately for builders who want one or the other or both. The bounding box that recurrent complex uses when selecting the structure to save it would be present in the world even after the structure is spawned naturally in the world. But cannot be seen by players unless they're a Moderator. And when the player is within the bounding box, placing and/or breaking blocks are disabled.

**Comment by Ivorforce** [comment]
Thank you for your suggestion! I have thought about this in the past as well and did consider implementing it.

However, Recurrent Complex has a strict philosophy of not being present when playing _at all_ and restricting itself to generation functionality. There were at some point plans for an addon mod to mitigate this - e.g. creating a dungeon dimension wherein all playing meddling is disabled, like in AdventureCraft - but due to lack of time it hasn't come to fruition. 

I think there are other mods that implement features like this, or at least add more indestructable blocks other than bedrock. I suggest checking those out as a sort of workaround, or trying your hand at individual dimensions as I suggested instead. I believe there may be mods capable of doing that exact thing, too.
